import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Wrapper from "@/layouts/Wrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rupam Majumder",
  description: "Generated by create next app",
  // icons:{
  //   icon : "/favicon.ico"
  // }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.png" type="image/png" sizes="512x512" />
      <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180" />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Wrapper>
        {children}
        </Wrapper>
      </body>
    </html>
  );
}
